[profile.default]
src = "src"
out = "out"
libs = ["lib"]
evm_version = "cancun"
bytecode_hash = "none"
cbor_metadata = false

remappings = [
    "@openzeppelin/uniswap-hooks/=lib/uniswap-hooks/",
    "@v4-periphery/=lib/v4-periphery/",
]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
